### ISSUE TITLE
Not able to create JAR File

### ISSUE THREAD

**Issue by manishareddy256** [sonar-xsl/Sonar-XSL-Plugin#22]
Hi - I am not able to create jar as I am getting below error, can you please check below and help me on this
If possible can you please upload the working jar file so that it will be very helpful

[ERROR] Failed to execute goal org.sonarxsl:sonar-schematron-packagin-plugin:1.0.0-SNAPSHOT:package-schematron-for-sonar
 (default) on project xslt-quality: Execution default of goal org.sonarxsl:sonar-schematron-packagin-plugin:1.0.0-SNAPSH
OT:package-schematron-for-sonar failed: A required class was missing while executing org.sonarxsl:sonar-schematron-packa
gin-plugin:1.0.0-SNAPSHOT:package-schematron-for-sonar: org/sonarxsl/SonarPackagingConstants
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.sonarxsl:sonar-schematron-packagin-plugin:1.0.0-SNAPSHOT
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/msolipuram/.m2/repository/org/sonarxsl/sonar-schematron-packagin-plugin/1.0.0-SNAPSHOT/
sonar-schematron-packagin-plugin-1.0.0-SNAPSHOT.jar
[ERROR] urls[1] = file:/C:/Users/msolipuram/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

**Comment by jimetevenard** [comment]
Hi,

Did you ensure that you launched `mvn package` from the root directory of the project ?

Your error message suggests that you were inside a submodule (xslt-quality) when you did run your command.

**Comment by manishareddy256** [comment]
Hi , when I have imported I got projects as below
[image: image.png]

and it was said that : The JAR to be installed in SonarQube will be
delivered at /sonar-xsl-plugin/target/sonar-xsl-plugin-1.x.x.jar
So I have followed the steps given but couldn't generate jar file.

Can you please help with this?
Thanks and Regards,
Manisha.

**Comment by manishareddy256** [comment]
Thank you for helping Jim, I could get the jar file now.
